force:
  proportional:
    x: 0.7 
    y: 0.7
    z: 4
  differential:
    x: 0.4
    y: 0.4
    z: 2.3

yawcontrol:
  proportional: 0.060
  differential: 0.005

rollcontrol:
  proportional: 1
  differential: 0.10

pitchcontrol:
  proportional: 1
  differential: 0.25

rate_damping:
  roll: -0.04
  pitch: 0.04

motorconst:
  const1: 0.35
  const2: 0.3832

rollconst:
  const: -0.050

pitchconst:
  const: 0.008

throttlecoef:
  coef1: 0.52
  coef2: 0.52

yawcoef:
  coef1: 0.0001
  coef2: 0.0001
