force:
  proportional:
    x: 0.7 
    y: 0.7
    z: 4
  differential:
    x: 0.4
    y: 0.4
    z: 2.3

yawmoment:
  proportional: 0.013893
  differential: 0.00166716

rate_damping:
  roll: -0.04
  pitch: 0.04

motorcoef:
  coef1: 0.35
  coef2: 0.3832

yawcoef:
  coef1: 0.52
  coef2: 0.52
